config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  resources :request_deadlines, only: [:new, :index, :create]
  resources :tickets
  resources :budgets, only: [:new, :index, :create]
  resources :requirements, only: [:new, :index, :create]
  get 'admin/panel'
  get 'admin/index'
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/budget.rb
class Budget < ApplicationRecord
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController  
  ##
  # GET /budgets
  #
  # GET /budgets.json
  #
  # @return [Array[Budget]] - Array contendo todos os budgets (orçamentos)
  #
  # Observação: o sistema mantém somente um budget cadastrado. Assim, quando um novo budget é inserido, o antigo é deletado.
  def index
    @budgets = Budget.all
  end

  ##
  # GET /budgets/new
  #
  # @return [Budget] - Uma instância vazia de budget.
  def new
    @budget = Budget.new
  end

  ##
  # POST /budgets
  #
  # POST /budgets.json
  #
  # O método cria um novo orçamento. Além disso, deleta todos orçamentos previamente existentes.
  #
  # @param [Float] value - Valor do orçamento
  #
  # Criação bem sucedida:
  #
  #   @return {status: 200, notice: 'Budget was successfully created'}
  #
  #   Efeitos colaterais: o registro é salvo na tabela 'budget', e o usuario é redirecionado para '/budgets
  #
  # Criação mal sucedida:
  #
  #   @return JSON {status: 422, errors: {...}}
  #
  #   Efeitos colaterais: o usuário é redirecionado para a rota '/budgets/new' e o erro retornado é exibido em tela.
  def create
    @budgets = Budget.all

    @budgets.each do |b|
      b.destroy
    end
    
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to '/budgets', notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    ##
    # Parâmetros recebidos pelo método.
    def budget_params
      params.require(:budget).permit(:value)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/index.html.erb
<% if user_signed_in? and current_user.role == 'administrator'%>  
  <p id="notice"><%= notice %></p>

  <h1>Orçamento</h1>

  <% if @budgets.count == 0 %>
    Não há orçamento cadastrado.
  <% else %>
    <h3>Valor disponível</h3>
    <% @budgets.each do |budget|%>  
      <h2 style="color:deeppink;"><%= budget.value %></h2>
    <% end %>
  <% end %>

  <br>

  <%= link_to 'Cadastrar orçamento atualizado', new_budget_path, style:"color:#3333ff;" %>
<% else %>
  <h1>Unauthorized</h1>
<% end %>

app/views/budgets/new.html.erb
<% if user_signed_in? and current_user.role == 'administrator'%>    
  <h1>New Budget</h1>

  <%= render 'form', budget: @budget %>

  <%= link_to 'Back', budgets_path %>
<% else %>
  <h1>Unauthorized</h1>
<% end %>