config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  resources :request_deadlines, only: [:new, :index, :create]
  resources :tickets
  resources :budgets, only: [:new, :index, :create]
  resources :requirements, only: [:new, :index, :create]
  get 'admin/panel'
  get 'admin/index'
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user

  validate :date_out_greater_than_in, on: [:create, :update]

  def date_out_greater_than_in
    if data_saida < data_entrada
      errors.add(:data_entrada, "cannot be greater than return date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  ##
  # Serve para buscar todas as diarias e envia as informações para a view
  # @return [@bookings] se existir
  def index
    @bookings = Booking.all
  end

  ##
  # Metodo serve apenas para view
  def show
  end

  ##
  # Metodo serve apenas para view
  def new
    @booking = Booking.new
  end

  ##
  # Metodo serve apenas para view
  def edit
  end

  ##
  # Metodo cria diarias
  # @param [Date] data_entrada
  # @param [Date] data_saida
  # Criação bem sucedida:
  #   @return { render :show, status: :created, location: @booking }
  # Criação mal sucedida:
  #   @return { render json: @booking.errors, status: :unprocessable_entity }
  def create
    @booking = Booking.new(booking_params)

    @booking.user = current_user

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Metodo atualiza diarias
  # @param [Date] data_entrada
  # @param [Date] data_saida
  # Criação bem sucedida:
  #   @return { render :show, status: :ok, location: @booking }
  # Criação mal sucedida:
  #   @return { render json: @booking.errors, status: :unprocessable_entity }
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Metodo destroi diarias
  # Criação bem sucedida:
  #   @return { head :no_content }
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:data_entrada, :data_saida)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_entrada %>
    <%= form.date_select :data_entrada%>
  </div>

  <div class="field">
    <%= form.label :data_saida %>
    <%= form.date_select :data_saida%>
  </div>

  <div class="actions">
    <%= form.submit value: "Solicitar diárias"%>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Data entrada</th>
      <th>Date saida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.data_entrada %></td>
        <td><%= booking.data_saida %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data entrada:</strong>
  <%= @booking.data_entrada %>
</p>

<p>
  <strong>Date saida:</strong>
  <%= @booking.data_saida %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>