config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  resources :request_deadlines, only: [:new, :index, :create]
  resources :tickets
  resources :budgets, only: [:new, :index, :create]
  resources :requirements, only: [:new, :index, :create]
  get 'admin/panel'
  get 'admin/index'
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/request_deadline.rb
class RequestDeadline < ApplicationRecord
  validate :deadline_greater_current_date, on: [:create, :update]

  def deadline_greater_current_date
    now = DateTime.now()
    
    if deadline < now      
      errors.add(:deadline, "cannot be less than current date")
    end
  end
end

app/controllers/request_deadlines_controller.rb
class RequestDeadlinesController < ApplicationController

  ##
  # Serve para buscar todas as deadlines e envia as informações para a view
  # @return [@request_deadlines] se existir
  def index
    @request_deadlines = RequestDeadline.all
  end

  ##
  # Metodo serve apenas para view
  def new
    @request_deadline = RequestDeadline.new
  end

  ##
  # Metodo cria DeadLines
  # @param [Date] deadline
  # Criação bem sucedida:
  #   @return { render :show, status: :created, location: @request_deadline }
  # Criação mal sucedida:
  #   @return { render json: @request_deadline.errors, status: :unprocessable_entity }
  def create
    @request_deadlines = RequestDeadline.all

    @request_deadlines.each do |r|
      r.destroy!
    end
    
    @request_deadline = RequestDeadline.new(request_deadline_params)

    respond_to do |format|
      if @request_deadline.save
        format.html { redirect_to '/request_deadlines', notice: 'O prazo para solitações foi definido com sucesso.' }
        format.json { render :show, status: :created, location: @request_deadline }
      else
        format.html { render :new }
        format.json { render json: @request_deadline.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def request_deadline_params
      params.require(:request_deadline).permit(:deadline)
    end
end

app/helpers/request_deadlines_helper.rb
module RequestDeadlinesHelper
end

app/views/request_deadlines/_form.html.erb
<%= form_with(model: request_deadline, local: true) do |form| %>
  <% if request_deadline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_deadline.errors.count, "error") %> prohibited this request_deadline from being saved:</h2>

      <ul>
      <% request_deadline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit value: "Definir prazo" %>
  </div>
<% end %>

app/views/request_deadlines/index.html.erb
<p id="notice"><% notice %></p>

<h1>Data limite para solicitações</h1>

<h3>O prazo atual para solicitações de passagens e diárias é:</h3>
<% @request_deadlines.each do |r| %>
  <%= r.deadline %>
<% end %>

<br>
<br>

<%= link_to 'Alterar o prazo para solicitação', new_request_deadline_path %>

app/views/request_deadlines/new.html.erb
<h1>New Request Deadline</h1>

<%= render 'form', request_deadline: @request_deadline %>

<%= link_to 'Back', request_deadlines_path %>