config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :bookings
  resources :request_deadlines, only: [:new, :index, :create]
  resources :tickets
  resources :budgets, only: [:new, :index, :create]
  resources :requirements, only: [:new, :index, :create]
  get 'admin/panel'
  get 'admin/index'
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  validate :date_out_greater_than_in, on: [:create, :update]

  def date_out_greater_than_in
    if data_saida < data_entrada
      errors.add(:data_entrada, "cannot be greater than return date")
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  ##
  # Serve para buscar todas as requisitos e envia as informações para a view
  # @return [@requirements] se existir
  def index
    @tickets = Ticket.all
  end

 
  ##
  # Metodo serve apenas para view
  def show
  end

  ##
  # Metodo serve apenas para view
  def new
    @ticket = Ticket.new
  end

  ##
  # Metodo serve apenas para view
  def edit
  end

  ##
  # Metodo cria ticket
  # @param [Date] data_entrada
  # @param [Date] data_saida
  # Criação bem sucedida:
  #   @return { render :show, status: :created, location: @ticket }
  # Criação mal sucedida:
  #   @return { render json: @ticket.errors, status: :unprocessable_entity }
  def create    
    @ticket = Ticket.new(ticket_params)

    @ticket.user = current_user

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Metodo atualiza solicitação
  # @param [Date] data_entrada
  # @param [Date] data_saida
  # Criação bem sucedida:
  #   @return { render :show, status: :ok, location: @ticket }
  # Criação mal sucedida:
  #   @return { render json: @ticket.errors, status: :unprocessable_entity }
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # Metodo destroi ticket
  # Criação bem sucedida:
  #   @return { head :no_content }
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:data_entrada, :data_saida)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_entrada %>
    <%= form.date_select :data_entrada, id: 'ticket_data_entrada' %>
  </div>

  <div class="field">
    <%= form.label :data_saida %>
    <%= form.date_select :data_saida %>
  </div>

  <div class="actions">
    <%= form.submit value:"Solicitar passagem" %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Data entrada</th>
      <th>Data saida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.data_entrada %></td>
        <td><%= ticket.data_saida %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>Nova passagem</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data entrada:</strong>
  <%= @ticket.data_entrada %>
</p>

<p>
  <strong>Data saida:</strong>
  <%= @ticket.data_saida %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>